#!/usr/bin/env ruby
Dir.glob("./*.gem").each { |path| `rm #{path}` }
puts `gem uninstall -x inverse_methods`
puts `gem build inverse_methods.gemspec`
Dir.glob("./*.gem").each { |path| puts `gem install -f #{path}` }
